import { useState, useEffect } from 'react';
import { Ic } from './icons.jsx';

const fs=()=>({width:'100%',background:'var(--inp)',color:'var(--txt)',border:'1.5px solid var(--brd)',borderRadius:8,padding:'8px 11px',fontSize:12.5,outline:'none',transition:'border-color .15s',fontFamily:'inherit'});

export function Fld({label,icon:I,children,hint}){return <div style={{display:'flex',flexDirection:'column',gap:4}}><label style={{fontSize:11,color:'var(--txtF)',fontWeight:500,display:'block',marginBottom:2}}>{I&&<span style={{display:'inline-flex',verticalAlign:'middle',marginRight:5,opacity:.7}}><I/></span>}{label}</label>{children}{hint&&<span style={{fontSize:10.5,color:'var(--txtD)'}}>{hint}</span>}</div>;}

export function TI({value,onChange,placeholder,type='text',prefix,...r}){const s=fs();if(prefix)return <div style={{display:'flex',alignItems:'center',background:'var(--inp)',border:'1.5px solid var(--brd)',borderRadius:8,overflow:'hidden'}} onFocusCapture={e=>e.currentTarget.style.borderColor='var(--acc)'} onBlurCapture={e=>e.currentTarget.style.borderColor='var(--brd)'}><span style={{padding:'8px 10px',background:'var(--surf2)',color:'var(--txtD)',fontSize:12,fontFamily:'monospace',whiteSpace:'nowrap',borderRight:'1.5px solid var(--brd)',flexShrink:0}}>{prefix}</span><input type={type} value={value} onChange={onChange} placeholder={placeholder} style={{...s,border:'none',borderRadius:0,flex:1,minWidth:0}} {...r}/></div>;return <input type={type} value={value} onChange={onChange} placeholder={placeholder} style={s} onFocus={e=>e.target.style.borderColor='var(--acc)'} onBlur={e=>e.target.style.borderColor='var(--brd)'} {...r}/>;}

export function Sel({value,onChange,children}){return <select value={value} onChange={e=>onChange(e.target.value)} style={{...fs(),cursor:'pointer',appearance:'none',backgroundImage:`url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%236b7280' stroke-width='2'%3E%3Cpolyline points='6 9 12 15 18 9'/%3E%3C/svg%3E")`,backgroundRepeat:'no-repeat',backgroundPosition:'right 10px center',paddingRight:28}}>{children}</select>;}

const ta=s=>({...fs(),resize:'vertical',lineHeight:1.5});

function UrlForm({value,onChange}){const raw=value.replace(/^https?:\/\//,'');const isH=!value.startsWith('http://');return<div style={{display:'flex',flexDirection:'column',gap:10}}><Fld label="URL" icon={Ic.Glo}><div style={{display:'flex',alignItems:'center',background:'var(--inp)',border:'1.5px solid var(--brd)',borderRadius:8,overflow:'hidden'}} onFocusCapture={e=>e.currentTarget.style.borderColor='var(--acc)'} onBlurCapture={e=>e.currentTarget.style.borderColor='var(--brd)'}><button onClick={()=>onChange((isH?'http://':'https://')+raw)} style={{padding:'8px 10px',background:'var(--surf2)',color:'var(--txtD)',fontSize:11.5,fontFamily:'monospace',border:'none',borderRight:'1.5px solid var(--brd)',cursor:'pointer',flexShrink:0,whiteSpace:'nowrap',outline:'none'}}>{isH?'https://':'http://'}</button><input type="text" value={raw} onChange={e=>onChange((isH?'https://':'http://')+e.target.value)} onBlur={e=>{const v=e.target.value;if(v&&!v.startsWith('http'))onChange('https://'+v);}} placeholder="www.example.com" style={{...fs(),border:'none',borderRadius:0,flex:1,minWidth:0}}/></div></Fld></div>;}

function EmailForm({value,onChange}){const parse=v=>{const m=v.match(/^mailto:([^?]*)(\?(.*))?$/);if(!m)return{addr:'',sub:'',body:''};const p=new URLSearchParams(m[3]||'');return{addr:m[1],sub:p.get('subject')||'',body:p.get('body')||''};};const build=(a,s,b)=>{const p=new URLSearchParams();if(s)p.set('subject',s);if(b)p.set('body',b);const q=p.toString();return'mailto:'+a+(q?'?'+q:'');};const{addr,sub,body}=parse(value);return<div style={{display:'flex',flexDirection:'column',gap:10}}><Fld label="Email address" icon={Ic.At}><TI prefix="mailto:" value={addr} onChange={e=>onChange(build(e.target.value,sub,body))} placeholder="name@example.com" type="email"/></Fld><Fld label="Subject" hint="Optional"><TI value={sub} onChange={e=>onChange(build(addr,e.target.value,body))} placeholder="Hello there"/></Fld><Fld label="Body" hint="Optional"><textarea value={body} onChange={e=>onChange(build(addr,sub,e.target.value))} rows={3} style={ta()} onFocus={e=>e.target.style.borderColor='var(--acc)'} onBlur={e=>e.target.style.borderColor='var(--brd)'} placeholder="Your message..."/></Fld></div>;}

function PhoneForm({value,onChange}){const n=value.replace(/^tel:/,'');return<div><Fld label="Phone number" icon={Ic.Phone}><TI prefix="tel:" value={n} onChange={e=>onChange('tel:'+e.target.value)} placeholder="+31612345678" type="tel"/></Fld></div>;}

function SmsForm({value,onChange}){const parse=v=>{const b=v.replace(/^(sms:|smsto:)/,'');const[n,r]=b.split('?');const p=new URLSearchParams(r||'');return{n,body:p.get('body')||''};};const build=(n,b)=>'sms:'+n+(b?'?body='+encodeURIComponent(b):'');const{n,body}=parse(value.startsWith('sms')?value:'sms:');return<div style={{display:'flex',flexDirection:'column',gap:10}}><Fld label="Phone number" icon={Ic.Phone}><TI prefix="sms:" value={n} onChange={e=>onChange(build(e.target.value,body))} placeholder="+31612345678" type="tel"/></Fld><Fld label="Pre-filled message" hint="Optional"><textarea value={body} onChange={e=>onChange(build(n,e.target.value))} rows={2} style={ta()} onFocus={e=>e.target.style.borderColor='var(--acc)'} onBlur={e=>e.target.style.borderColor='var(--brd)'} placeholder="Your message..."/></Fld></div>;}

function WifiForm({onChange}){
  const[ssid,setSsid]=useState('');const[pass,setPass]=useState('');const[sec,setSec]=useState('WPA');const[hidden,setHidden]=useState(false);const[show,setShow]=useState(false);
  const esc=v=>v.replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/"/g,'\\"');
  const emit=(t,s,p,h)=>{let str='WIFI:S:'+esc(s)+';T:'+t+';P:'+esc(p)+';';if(h)str+='H:true;';str+=';;';onChange(str);};
  useEffect(()=>emit(sec,ssid,pass,hidden),[]);
  const hS=v=>{setSsid(v);emit(sec,v,pass,hidden);};const hP=v=>{setPass(v);emit(sec,ssid,v,hidden);};const hT=v=>{setSec(v);emit(v,ssid,pass,hidden);};const hH=v=>{setHidden(v);emit(sec,ssid,pass,v);};
  return<div style={{display:'flex',flexDirection:'column',gap:10}}><Fld label="Network name (SSID)" icon={Ic.Wifi}><TI value={ssid} onChange={e=>hS(e.target.value)} placeholder="My Network"/></Fld><Fld label="Security type"><Sel value={sec} onChange={hT}><option value="WPA">WPA / WPA2 / WPA3</option><option value="WEP">WEP</option><option value="nopass">None (open)</option></Sel></Fld>{sec!=='nopass'&&<Fld label="Password" icon={Ic.Lk}><div style={{display:'flex',alignItems:'center',background:'var(--inp)',border:'1.5px solid var(--brd)',borderRadius:8,overflow:'hidden'}} onFocusCapture={e=>e.currentTarget.style.borderColor='var(--acc)'} onBlurCapture={e=>e.currentTarget.style.borderColor='var(--brd)'}><input type={show?'text':'password'} value={pass} onChange={e=>hP(e.target.value)} placeholder="Password" style={{...fs(),border:'none',borderRadius:0,flex:1,minWidth:0}}/><button onClick={()=>setShow(x=>!x)} style={{padding:'0 10px',background:'none',border:'none',color:'var(--txtD)',cursor:'pointer',display:'flex',alignItems:'center'}}>{show?<Ic.EyeX/>:<Ic.Eye/>}</button></div></Fld>}<label style={{display:'flex',alignItems:'center',gap:8,cursor:'pointer',fontSize:12,color:'var(--txtM)'}}><input type="checkbox" checked={hidden} onChange={e=>hH(e.target.checked)} style={{width:14,height:14,accentColor:'var(--acc)'}}/>Hidden network</label></div>;
}

function TxtForm({value,onChange}){return<div style={{display:'flex',flexDirection:'column',gap:10}}><Fld label="Text content" icon={Ic.Txt}><textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} style={{...ta(),lineHeight:1.6}} placeholder="Enter any text..." onFocus={e=>e.target.style.borderColor='var(--acc)'} onBlur={e=>e.target.style.borderColor='var(--brd)'}/></Fld><div style={{display:'flex',justifyContent:'flex-end'}}><span style={{fontSize:10.5,fontFamily:'monospace',color:value.length>270?'var(--dan)':'var(--txtD)'}}>{value.length}/300</span></div></div>;}

export function CForm({type,value,onChange}){if(type==='url')return<UrlForm value={value} onChange={onChange}/>;if(type==='email')return<EmailForm value={value} onChange={onChange}/>;if(type==='phone')return<PhoneForm value={value} onChange={onChange}/>;if(type==='sms')return<SmsForm value={value} onChange={onChange}/>;if(type==='wifi')return<WifiForm onChange={onChange}/>;return<TxtForm value={value} onChange={onChange}/>;}
